import "./globals.css";

import { Inter } from "next/font/google";

if (process.env.NEXT_PUBLIC_API_MOCKING === "enabled") {
  require("../mocks");
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative mx-auto min-h-[100vh] max-w-[44rem] bg-white shadow-lg">
          {children}
        </main>
      </body>
    </html>
  );
}
